version: '2'
services:

  prod:
    image: tomcat:latest
    links:
      - dev
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/???
    volumes_from:
      - dev
    
    depends_on:
      - dev

  dev:
    build: php-7.0-fpm-custom
    environment:
      - TYPO3_CONTEXT=Development/Docker
    links:
      - db
      - redis
    volumes:
      - ./htdocs:/var/www/html

  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:latest
