version: '3'
services:

  prod:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - webapp:/webapps

  dev:
    build: ./dev
    volumes:
      - webapp:/home/war
    depends_on:
      - prod
      
volumes:
  webapp:
